version: '2'
services:
  tomato-web:
    build: .
    ports:
      - "8080:8080"
    command:
      /bin/sh -c "python3 manage.py initialize && python3 manage.py import_root_servers"
    environment:
      RDS_HOST: postgis
    links:
      - postgis
  tomato-daemon:
    build: .
    command:
      /bin/sh -c "python3 manage.py initialize && uwsgi --master --http 0.0.0.0:8000 --module tomato.wsgi --processes 32"
    environment:
      RDS_HOST: postgis
    links:
      - postgis
  postgis:
    image: mdillon/postgis:9.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tomato
      POSTGRES_USER: tomato
      POSTGRES_PASSWORD: tomato
  semantic-workshop:
    image: radius314/bmlt-semantic-workshop:1.3.2
    ports:
      - "8081:80"
