version: '2'
services:
  postgis:
    image: mdillon/postgis:9.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tomato
      POSTGRES_USER: tomato
      POSTGRES_PASSWORD: tomato
  tomato-web:
    build: .
    ports:
      - "8000:8000"
    command:
      /bin/sh -c "sleep 60 && python3 manage.py initialize && uwsgi --ini /code/uwsgi.ini"
    environment:
      RDS_HOST: postgis
    links:
      - postgis
    volumes:
      - "./src/tomato:/code/tomato"
  #tomato-daemon:
  #  build: .
  #  command:
  #    /bin/sh -c "sleep 60 && python3 manage.py initialize && python3 manage.py import_root_servers"
  #  environment:
  #    RDS_HOST: postgis
  #  links:
  #    - postgis
  #semantic-workshop:
  #  image: bmlt-enabled/bmlt-semantic-workshop:1.3.2
  #  ports:
  #    - "8001:80"
  #  links:
  #    - tomato-web
